apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.store.name }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.store.name }}
