version: "3.8"

services:

  db:
    container_name: db
    image: postgres:12.8
    volumes:
      - database:/var/lib/postgresql/bookdata/
    ports:
      - 5432:5432
    restart: always
    tty: true
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  store:
    container_name: bookstore
    image: "bookstore:1.0.0"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8000"
    env_file:
      - app/.env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  database: